version: "3.7"
services:
  db: 
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wallet_api
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=secretpassword
      - MYSQL_ROOT_PASSWORD=verysecretpassword
    networks:
      - database
  
  api:
    # TODO: replace later with docker image
    build: 
      dockerfile: dockerfile
      context: .
    ports:
      - 5000:5000
    networks: 
      - database
      - api
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:5000"]
      interval: 5s
      timeout: 3s
      retries: 3
    # TODO: healthcheck

networks:
  - database
  - api